sudo: required
language: node_js

node_js:
  - 'lts/*'

cache:
  yarn: true
  directories:
    - 'node_modules'

jobs:
  include:
    - stage: gh-pages
      node_js: lts/*
      script:
        - yarn run lint
      before_deploy:
        - yarn run docs:build
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        keep-history: true
        local-dir: 'gh-pages'
        on:
          branch: master
    - stage: semantic-release
      node_js: lts/*
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
        on:
          branch: master
